name: Build
on: push

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Build and release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build-ci
      - name: Run tests
        run: npm run test-ci
      - name: Release
        if: github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
